name: "pre-release"

on:
  push:
    branches:
      - "main"
    tags-ignore:
      - "*"

jobs:
  pre-release:
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Pack files
        run: |
          while IFS= read -r asset_bin_dir; do
            asset_dir="$(dirname "${asset_bin_dir}")"
            asset_name="$(basename "${asset_dir}")"
            mkdir -p ./dist
            tar -C "${asset_dir}" -cvzf "./dist/${asset_name}.tar.gz" .
            sha512sum "./dist/${asset_name}.tar.gz" | tee "./dist/${asset_name}-sha512sum.txt"
          done < <(find . -mindepth 2 -maxdepth 2 -type d \( -path ./.git -o -path ./.github \) -prune -o -type d -name 'bin' -print)

      - name: "Release"
        id: "automatic_releases"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            dist/*
